=== xTheshi/XD/menu.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT menu (dania,napoje)>
<!ELEMENT dania (kebab,zestaw,inne_dania)>
<!ELEMENT kebab (na_cienkim,na_grubym,na_talerzu)>
<!ELEMENT zestaw (nazwa+,cena+,dodatki)>
<!ELEMENT inne_dania (nazwa,cena)>
<!ELEMENT napoje (nazwa,rozmiar,cena)>
	
<!ELEMENT na_cienkim (mieso,rozmiar,sos,cena+)>
<!ELEMENT na_grubym (mieso,rozmiar,sos,cena+)>
<!ELEMENT na_talerzu (mieso,rozmiar,sos,cena+)>

<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT dodatki (#PCDATA)>
<!ELEMENT mieso (#PCDATA)>
<!ELEMENT rozmiar (#PCDATA)>
<!ELEMENT sos (#PCDATA)>

=== xTheshi/XD/zamowienie.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
	<dania>
		<kebab>
			<na_cienkim>
				<mieso></mieso>
				<rozmiar></rozmiar>
				<sos></sos>
				<cena></cena>
			</na_cienkim>
			<na_grubym>
				<mieso></mieso>
				<rozmiar></rozmiar>
				<sos></sos>
				<cena></cena>
			</na_grubym>
			<na_talerzu>
				<mieso></mieso>
				<rozmiar></rozmiar>
				<sos></sos>
				<cena></cena>
			</na_talerzu>
		</kebab>
		<zestaw>
			<nazwa></nazwa>
			<cena></cena>
			<dodatki></dodatki>
		</zestaw>
		<inne_dania>
			<nazwa></nazwa>
			<cena></cena>
		</inne_dania>
	</dania>
	<napoje>
			<nazwa></nazwa>
			<rozmiar></rozmiar>
			<cena></cena>
	</napoje>
</menu>
